name: flake8 Lint

on: [push, pull_request]

jobs:

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          args: "--max-line-length=99 --ignore B008,E121,E123,E126,E226,E24,E704,W503,W504,D100,D105,D200,D301,D402,F811,F841"
          exclude: "./lib"